#!/usr/bin/spargo

ENDPOINT=https://query.wikidata.org/sparql

# Wikidata and FDD link to fmt/134
SELECT ?format ?puid ?ldd WHERE
{
  ?format wdt:P2748 "fmt/134".
  ?format wdt:P2748 ?puid .
  ?format wdt:P3266 ?ldd .
}
